services:
  postgres: #Config para DB Postgres
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network #Define rede local

  pgadmin: #Config para o PGAdmin (Interface administrativa do Postgres)
    image: dpage/pgadmin4:9.11
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: dba@demodelivery.com
      PGADMIN_DEFAULT_PASSWORD: demodelivery
    ports:
      - 8083:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  local-network:
    driver: bridge