server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.demoworks: DEBUG

spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092 #Endereço do broker Kafka para onde as mensagens serão enviadas
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: #Mapeamento de eventos para o Kafka, onde a chave é o nome do evento e o valor é a classe do evento correspondente.
          delivery-placed-event:com.demoworks.demodelivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.demoworks.demodelivery.delivery.tracking.domain.event.DeliveryPickedUpEvent,
          delivery-fullfilled-event:com.demoworks.demodelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent

#Configurações para o cliente Eureka, que é usado para registro e descoberta de serviços em um ambiente de microserviços.
eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/ #URL do servidor Eureka para registro do serviço
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

#Config da politica de retry do Resilience4j
resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 20ms
      instances:
        Retry_CourierAPIClient_payoutCalculation:
          baseConfig: default
          maxAttempts: 3
          retryExceptions:
            - org.springframework.web.client.ResourceAccessException
          ignoreExceptions:
            - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    configs: #Configuracao para o circuit braker (baseada emc ontagem), que diz que se 10 chamadas forem feitas e 5 falharem (50%) entao o circuito é aberto
      default:
        slidingWindowType: COUNT_BASED #TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CircuitBreaker_CourierAPIClient_payoutCalculation:
        baseConfig: default
        waitDurationInOpenState: 5000

#Variaveis de ambiente do sistema
courier:
  api.base-instance-url: http://courier-management