server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.demoworks: DEBUG

spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092 #Endereço do broker Kafka para onde as mensagens serão enviadas
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: #Mapeamento de eventos para o Kafka, onde a chave é o nome do evento e o valor é a classe do evento correspondente.
          delivery-placed-event:com.demoworks.demodelivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.demoworks.demodelivery.delivery.tracking.domain.event.DeliveryPickedUpEvent,
          delivery-fullfilled-event:com.demoworks.demodelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent

#Configurações para o cliente Eureka, que é usado para registro e descoberta de serviços em um ambiente de microserviços.
eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/ #URL do servidor Eureka para registro do serviço
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

#Variaveis de ambiente do sistema
courier:
  api.base-instance-url: http://courier-management